# Generated by Django 5.0.4 on 2024-12-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_newsimages_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'В обработке'), ('ready', 'Готов'), ('completed', 'Выполнен'), ('cancelled', 'Отменён')], default='pending', max_length=20),
        ),
    ]
